blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from accounts.views import (
    login_view,
    logout_view,
    register_view,
    )
from rest_framework_jwt.views import obtain_jwt_token

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls",namespace = 'posts')),
    url(r'^comments/', include("comments.urls",namespace = 'comments')),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^register/', register_view, name='register'),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api/posts/', include("posts.api.urls", namespace = 'posts_api')),
    url(r'^api/comments/', include("comments.api.urls", namespace = 'comments_api')),
    url(r'^api/accounts/', include("accounts.api.urls", namespace = 'accounts_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/api/urls.py
from django.conf.urls import url
from .views import (
	PostListAPIView,
	PostDetailAPIView,
	PostUpdateAPIView,
	PostDeleteAPIView,
	PostCreateSerializer,
	)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^create/$', PostCreateSerializer.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
]

posts/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
	post_create,
	post_detail,
	post_list,
	post_update,
	post_delete,
	)

urlpatterns = [
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^$', post_list, name='list'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
]

posts/models.py
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe
from comments.models import Comment
from django.contrib.contenttypes.models import ContentType
# Create your models here.

class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		#Post.objects.all() = super(PostManager,self).all()
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())
def upload_location(instance,filename):
	print "%s/%s" %(instance.pk, filename)
	return "%s/%s" %(instance.pk, filename)
class Post(models.Model):
	title = models.CharField(max_length=30)
	content = models.TextField()
	draft = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	#image = models.FileField(null=True, blank=True)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field='width_field', height_field='height_field')
	width_field = models.IntegerField(default=0)
	height_field = models.IntegerField(default=0)
	#updated = models.DateTimeField(auto_now=True, auto_now_add=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)


	objects = PostManager()


	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		#return "/posts/%s/" %(self.id)
		#return reverse('posts:detail', kwargs={'id':self.id})
		return reverse('posts:detail', kwargs={'slug':self.slug})
	class Meta:
		ordering = ['-timestamp']

	def get_markdown(self):
		content = self.content
		marked_content = markdown(content)
		marked_content_safe =mark_safe(marked_content )
		return marked_content_safe

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs



def create_slug(instance, new_slug=None):
	slug = slugify(instance.title)
	if new_slug is not None:
		slug = new_slug
	qs = Post.objects.filter(slug=slug).order_by('-id')
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug
def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)

pre_save.connect(pre_save_post_receiver, sender=Post)

posts/forms.py
from django import forms
from .models import Post
from django.forms import extras
from pagedown.widgets import PagedownWidget

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=extras.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
		'title',
		'content',
		'image',
		'draft',
		'publish',
		]

posts/api/views.py
from rest_framework.generics import (
	ListAPIView,
	DestroyAPIView,
	RetrieveAPIView,
	RetrieveUpdateAPIView,
	UpdateAPIView,
	CreateAPIView,
	)
from rest_framework.permissions import(
	AllowAny,
	IsAuthenticated,
	IsAdminUser,
	IsAuthenticatedOrReadOnly,
	)
from .permissions import IsOwnerOrReadOnly
from posts.models import Post
from .serializers import (
	PostListSerializer,
	PostDetailSerializer,
	PostCreateUpdateSerializer,
	)
from django.db.models import Q
from rest_framework.filters import(
	SearchFilter,
	OrderingFilter,
	)
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination


class PostCreateSerializer(CreateAPIView):
	queryset  = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer 
	permission_classes = [IsAuthenticated]
	def perform_create(self, serializer):
		serializer.save(user=self.request.user)

class PostListAPIView(ListAPIView):
	serializer_class = PostListSerializer
	filter_backends = (SearchFilter, OrderingFilter)
	search_fields = ('title', 'content', 'user__first_name',)
	pagination_class = PostPageNumberPagination
	def get_queryset(self):
		queryset_list  = Post.objects.all()
		query = self.request.GET.get('q')
		if query:
			queryset_list = queryset_list.filter(
			Q(title__icontains=q)|
			Q(content__icontains=q)|
			Q(user__first_name__icontains=q)|
			Q(user__last_name__icontains=q)
			).distinct()
		return queryset_list

class PostDetailAPIView(RetrieveAPIView):
	queryset  = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'

class PostUpdateAPIView(RetrieveUpdateAPIView):
	queryset  = Post.objects.all()
	serializer_class = PostCreateUpdateSerializer
	lookup_field = 'slug'
	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
	def perform_update(self, serializer):
		serializer.save(user=self.request.user)

class PostDeleteAPIView(DestroyAPIView):
	queryset  = Post.objects.all()
	serializer_class = PostDetailSerializer
	lookup_field = 'slug'
	permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

posts/views.py
from urllib import quote_plus
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.contrib.contenttypes.models import ContentType
# Create your views here.
from .models import Post
from .forms import PostForm
from comments.models import Comment
from django.utils import timezone
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from comments.forms import CommentForm
def post_create(request):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	form = PostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		instance = form.save(commit = False)
		instance.user = request.user
		print form.cleaned_data.get('title')
		instance.save()
		messages.success(request, "Successfully created")
		return HttpResponseRedirect(instance.get_absolute_url())
		#print request.POST.get('content')
		#rint request.POST.get('title')
	else:
		messages.error(request, "Not successfully created")
	context = {'form':form}
	return render(request, 'post_form.html', context)

def post_detail(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	if instance.draft or instance.publish > timezone.now().date():
		if not request.user.is_staff or not request.user.is_superuser:
			raise Http404
	#share_string = quote_plus(instance.content)
	initial_data={
		"content_type":instance.get_content_type,
		"object_id":instance.id,
	}
	comment_form = CommentForm(request.POST or None, initial=initial_data)
	if comment_form.is_valid() and request.user.is_authenticated():
		print(comment_form.cleaned_data)
		content_type_model = comment_form.cleaned_data.get("content_type")
		content_type = ContentType.objects.get(model=content_type_model)
		object_id = comment_form.cleaned_data.get("object_id")
		content = comment_form.cleaned_data.get("comment")
		parent_obj = None
		try:
			parent_id = request.POST.get("parent_id")
		except:
			parent_id = None
		if parent_id:
			parent_qs = Comment.objects.filter(id=parent_id)
			if parent_qs.exists() and parent_qs.count()==1:
				parent_obj = parent_qs.first()

		new_comment, created = Comment.objects.get_or_create(
			user = request.user,
			content_type = content_type,
			object_id = object_id,
			content = content,
			parent = parent_obj,
			)
		if created:
			print('it worked')
		return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

	comments = instance.comments#Comment.objects.filter_by_instance(instance)
	context = {'title':instance.title, 'instance':instance, 'comments':comments,'comment_form':comment_form}#, 'share_string':share_string}
	return render(request, 'post_detail.html', context)

def post_list(request):
	today = timezone.now()
	queryset_list = Post.objects.active()#.order_by('-timestamp')
	if request.user.is_staff or request.user.is_superuser:
		queryset_list = Post.objects.all()	
	title = 'List'
	q = request.GET.get('q')
	if q:
		queryset_list = queryset_list.filter(
			Q(title__icontains=q)|
			Q(content__icontains=q)|
			Q(user__first_name__icontains=q)|
			Q(user__last_name__icontains=q)
			).distinct()#no distinct posts
	paginator = Paginator(queryset_list, 5)
	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)
	context = {'queryset':queryset, 'title':title,'today':today}
	return render(request, 'post_list.html', context)
  
def post_update(request, slug=None):
	if not request.user.is_staff or not request.user.is_superuser:
		raise Http404
	instance = get_object_or_404(Post, slug=slug)
	form = PostForm(request.POST or None, request.FILES or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit = False)
		print form.cleaned_data.get('title')
		instance.save()
		messages.success(request, "Saved", extra_tags='some-tag')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {'form':form}
	return render(request, 'post_form.html', context)

def post_delete(request, slug=None):
	instance = get_object_or_404(Post, slug=slug)
	instance.delete()
	messages.success(request, "Deleted.")
	return redirect("posts:list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load staticfiles %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
	<title>{% block head_title %}Tiny Pencil{% endblock %}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel='stylesheet' href="{% static 'css/main.css' %}">
	{% block head_extra %}{% endblock %}
</head>
<body>
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
 	 var js, fjs = d.getElementsByTagName(s)[0];
  	if (d.getElementById(id)) return;
  	js = d.createElement(s); js.id = id;
  	js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11';
 	 fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
		<div class="container">
			<a class="navbar-brand" href="index.html">TINY PENCIL</a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				<i class="fa fa-bars"></i>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="{% url 'posts:list' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'posts:list' %}">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'register' %}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'login' %}">Login</a>
					</li>
					<li class="nav-item">
					<a class="nav-link" href="{% url 'logout' %}">Logout</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'posts:list' %}">Contact</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	{% block header %}
    {% endblock %}
	{% include 'messages.html' %}
	<div class="container">
		<ol class="breadcrumb">
  			<li class="breadcrumb-item"><a href="{% url 'posts:list' %}">Home</a></li>
  			{% block post_detail_link %}
  			{% endblock %}
		</ol>
		{% block content %}
		{% endblock %}
	</div>
	<footer>
		<div class="container">
			<div class="row">
 				<div class="col-lg-8 col-md-10 mx-auto">
					<ul class="list-inline text-center">
						<li class="list-inline-item">
							<a href="#">
								<span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
								</span>
							</a>
						</li>
						<li class="list-inline-item">
							<a href="#">
								<span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
								</span>
							</a>
						</li>
						<li class="list-inline-item">
							<a href="#">
								<span class="fa-stack fa-lg">
									<i class="fa fa-circle fa-stack-2x"></i>
									<i class="fa fa-github fa-stack-1x fa-inverse"></i>
								</span>
							</a>
						</li>
					</ul>
					<p class="copyright text-muted">Copyright &copy; www.tinypencil.co 2018</p>
				</div>
			</div>
		</div>
	</footer>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	<script type="text/javascript">
		$(document).ready(function(){
			$('.content-markdown').each(function(){
				var content = $(this).text();
				var mark = marked(content);
				$(this).html(mark);
			});
			$('.post-detail-item img').each(function(){
				$(this).addClass('img-fluid');
			});
			var titleItem = $('#id_title');
			$('#preview-title').text(titleItem.val());

			var contentItem = $('#id_content');
			function setContent(value){
				var markedContent = marked(value)
				$('#preview-content').html(markedContent);
				$('#preview-content img').each(function(){
					$(this).addClass('img-fluid');
				});
			};
			setContent(contentItem.val())
			contentItem.keyup(function(){
				var newContent = $(this).val();
				setContent(newContent);
			});
			$(".comment-reply-btn").click(function(event){
				event.preventDefault();
				$(this).parent().next(".comment-reply").fadeToggle();
			});
			
		});	
	</script>
</body>
</html>

templates/comment_detail.html
{% extends 'base.html' %}
{% block head_title %} {{ instance.title }} | {{block.super }} {% endblock %}
{% load crispy_forms_tags %}
{% block post_detail_link %}
	<li class="breadcrumb-item"><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-5 mx-auto">
				<p>{{ comment.content }}</p>
				<footer>via {{ comment.user }} | {{comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comments {% endif %}<a href="#" class="comment-reply-btn">Reply |</a>{% if comment.user == request.user %}<a href="{{ comment.get_delete_url }}"> Delete</a>{% endif %}</footer>
				<hr>
				<div class="comment-reply">
					{% for child_comment in comment.children %}
					<blockquote>
						<p>{{ child_comment.content }}</p>
						<footer>via {{ child_comment.user }} | {{child_comment.timestamp|timesince }} ago |{% if child_comment.user == request.user %}<a href="{{ child_comment.get_delete_url }}"> Delete</a>{% endif %}</footer>
					</blockquote>
					{% endfor %}
					<form method="POST" action="">
						{% csrf_token %}
						{{ comment_form|crispy}}
						<input type="hidden" name="parent_id" value="{{ comment.id }}">
						<input type="submit" name="submit" class="btn btn-default" value="Reply">
						<br>
					</form>
				</div>
			<hr>
	</div>
</div>
{% endblock %}

templates/confirm_delete.html
{% extends 'base.html' %}
{% block head_title %} {{ instance.title }} | {{block.super }} {% endblock %}
{% load crispy_forms_tags %}
{% block post_detail_link %}
	<li class="breadcrumb-item"><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-5 mx-auto">
		<h1>Confirm Delete</h1>
		<form method="POST" action="">
			{% csrf_token %}
			<p>Are you sure you want to delete: "{{ instance.content }}" ?</p>
			<input type="submit" name="Confirm" class="btn btn-warning" value="Confirm">
			<a href="{{ instance.get_absolute_url }}" class="btn btn-default">Cancel</a>
			<br>
		</form>
		<hr>
	</div>
</div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}{{title}} | {{block.super }} {% endblock %}
{% block header %}
<header class="masthead" style="background-image: url('img/home-bg.jpg')">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
				<div class="site-heading">
					<h1>{{ title }}</h1>
				</div>
			</div>
		</div>
	</div>
</header>
{% endblock %}
{% block post_detail_link %}
	<li class="breadcrumb-item"><a href="{{ instance.get_absolute_url }}">{{ title }}</a></li>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-5 mx-auto">
		<h1>{{ title }} Here!</h1>
		<form method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy}}
			<input type="submit" name="submit" class="btn btn-default" value="{{title}}">
		</form>
	</div>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
<div class="row">
	<div class="col-lg-8 col-md-10 mx-auto">
		<div class="messages">
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
  				<ul class="messages list-unstyled">
	    		{% for message in messages %}
	    			<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    		{% endfor %}
				</ul>
  				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
		</div>
	</div>
</div>
{% endif %}

templates/post_detail.html
{% extends 'base.html' %}
{% block head_title %} {{ instance.title }} | {{block.super }} {% endblock %}
{% load crispy_forms_tags %}
{% block header %}
<header class="masthead" style="background-image: url('img/post-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>{{ instance.title }}</h1>
              <span class="meta">Posted
					{% if instance.user.get_full_name %}
					 by
					<a href="#">
						{{ instance.user.get_full_name }}
					</a>
					{% endif %}
					on
					{{ instance.publish }}</span>
            </div>
          </div>
        </div>
      </div>
</header>	
{% endblock %}
{% block post_detail_link %}
	<li class="breadcrumb-item"><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-lg-8 col-md-10 mx-auto">
		{% if instance.image %}
			<img src="{{ instance.image.url }}" class="img-fluid" alt="Responsive image">
		{% endif %}
		<h1>{{ title }} <small>{% if instance.draft %}<span style='color:red;'>Draft </span>{% endif %}{{ instance.publish }}</small></h1>
		{% if instance.user.get_full_name %}
		<p>Author: {{ instance.user.get_full_name }}</p>
		{% endif %}
		<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
		<p>
			<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}"><i class="fa fa-facebook-official" aria-hidden="true"></i>
			</a>
			<a href="https://twitter.com/home?status={{ share_string }}%20{{ request.build_absolute_uri }}"> <i class="fa fa-twitter" aria-hidden="true"></i>
			</a>
			<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'> <i class="fa fa-google-plus" aria-hidden="true"></i>
			</a>
			<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title }}&summary={{ share_string }}&source={{ request.build_absolute_uri }}"> <i class="fa fa-linkedin" aria-hidden="true"></i>
			</a>
			<a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ instance.title }}"> <i class="fa fa-reddit-alien" aria-hidden="true"></i>
			</a>	
		</p>
		<hr>
		<div class="row">
			<div class='col-sm-12'>
				<div class="post-detail-item">{{ instance.get_markdown | linebreaks }}
				<br>
				</div>
				<hr>
				<br>
				<div >
				<p class="lead">Comments</p>
				{% if request.user.is_authenticated %}
					<form method="POST" action="">
						{% csrf_token %}
						{{ comment_form|crispy}}
						<input type="submit" name="submit" class="btn btn-default" value="Post comment">
						<br>
					</form>
				{% else %}
					<p>You must Login to comment</p>
				{% endif %}
				{% for comment in comments %}
				<blockquote>
					<p>{{ comment.content }}</p>
					<footer>- via {{ comment.user }} | {{comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comments {% endif %}<a href="#" class="comment-reply-btn">Reply </a>|<a href="{{ comment.get_absolute_url }}" class=""> Thread</a>
					</footer>
					<div class="comment-reply">
						{% for child_comment in comment.children %}
						<blockquote>
							<p>{{ child_comment.content }}</p>
							<footer>via {{ child_comment.user }} | {{child_comment.timestamp|timesince }} ago
							</footer>
						</blockquote>
						{% endfor %}
						{% if request.user.is_authenticated %}
						<form method="POST" action="">
							{% csrf_token %}
							{{ comment_form|crispy}}
							<input type="hidden" name="parent_id" value="{{ comment.id }}">
							<input type="submit" name="submit" class="btn btn-default" value="Reply">
							<br>
						</form>
						{% else %}
						<p>You must Login to comment</p>
						{% endif %}
					</div>
				</blockquote>
				<hr>
				{% endfor %}
				</div>
			</div>
			<!--<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5">
			</div>-->
		</div>
	</div>
</div>
{% endblock %}

templates/post_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}form | {{block.super }} {% endblock %}
{% block head_extra %} {{ form.media }}
<style>.wmd-panel{
	margin-left: 0px;
	margin-right: 0px;
}
</style>
{% endblock %}
{% block header %}
<header class="masthead" style="background-image: url('img/post-bg.jpg')">
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1>Create a post.</h1>
              <span class="meta">Write a thought!</span>
            </div>
          </div>
        </div>
      </div>
</header>	
{% endblock %}
{% block post_detail_link %}
	<li class="breadcrumb-item"><a href="{% url 'posts:create' %}">Create</a></li>
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-sm-5 mx-auto">
		<h1>Preview</h1>
		<div class="content-preview">
			<h3 id="preview-title"></h3>
			<p id="preview-content"></p>
		</div>
	</div>
	<div class="col-sm-5 mx-auto">
		<h1>Form</h1>
		<form method="POST" action="" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form|crispy}}
			<input type="submit" name="submit" class="btn btn-default" value="Create post">
		</form>
		<hr>
	</div>
</div>

{% endblock %}